<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="chassis">
  <!-- Base Properties -->
  <xacro:property name="mass_base" value="340" />
  <xacro:property name="base_x_size" value="1.8000" />
  <xacro:property name="base_y_size" value="1.80000" />
  <xacro:property name="base_z_size" value="0.66000" />

  <xacro:property name="wheelbase" value="2" />
  <xacro:property name="track" value="2" />

  <xacro:macro name="chassis">
    <!-- Base footprint is on the ground under the robot -->
    <gazebo reference="base_footprint">
      <material>Gazebo/Grey</material>
    </gazebo>
    <link name="base_footprint">
    <inertial>
      <origin xyz="0 0 1" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="100.0" ixy="10.0" ixz="10.0"
        iyy="100.0" iyz="10.0"
        izz="100.0"/>
    </inertial>
    </link>

    <gazebo reference="base_link">
      <material>Gazebo/Grey</material>
    </gazebo>
    <!-- Base link is the center of the robot's bottom plate -->
    <link name="base_link">
      <inertial>
        <mass value="340" />
        <origin xyz="0 0 0" />
        <inertia ixx="${mass_base/12.0 * (base_y_size*base_y_size + base_z_size*base_z_size)}" ixy="1" ixz="1"
                 iyy="${mass_base/12.0 * (base_x_size*base_x_size + base_z_size*base_z_size)}" iyz="1"
                 izz="${mass_base/12.0 * (base_y_size*base_y_size + base_x_size*base_x_size)}" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
        </geometry>
        <material name="grey">
          <color rgba="0.6 0.6 0.6 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
        </geometry>
      </collision>
    </link>
    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 ${ground_clearance + base_z_size/2}" rpy="0 0 0" />
      <child link="base_link" />
      <parent link="base_footprint" />
    </joint>
  </xacro:macro>
</robot>
